name: Dependabot auto-merge

on:
  workflow_call:
    inputs:
      pr_url:
        required: true
        type: string
      login:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependabot:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ inputs.pr_url }}
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - name: Assign PRs to me
        run: gh pr edit --add-assignee $LOGIN "$PR_URL"
        env:
          LOGIN: ${{ inputs.login }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
